In [1]:
import pandas as pd

from plastic_neuron import PlasticNeuron
from neuron import h

In [2]:
neuron = PlasticNeuron()

Creating cell
	1
	1
	0
23
After any change to cell geometry or nseg, be sure to invoke setpointers()
	1
Generating synapse information
Inserting 10 synapses

In [3]:
neuron.synapse_info.to_csv("synapses.csv")

In [4]:
synapses = pd.read_csv("synapses.csv")
synapses

   Unnamed: 0  Dendrite  Location    Distance      Delay
0           0        14  0.139538  116.315870  10.249518
1           1         5  0.590493  184.839315   3.178268
2           2         5  0.218638  125.874136  50.535529
3           3        28  0.589266  287.073876  80.943046
4           4        21  0.277871  179.285582  21.531376
5           5         5  0.379927  149.460208  35.897938
6           6        22  0.603726  160.043804  80.712827
7           7         7  0.973116  210.756824  37.853438
8           8        23  0.577352  255.118383  70.457184
9           9         2  0.661263  184.257752  77.306834

In [5]:
neuron = PlasticNeuron(
    synapse_info = synapses
)

Creating cell
	1
	1
	0
23
After any change to cell geometry or nseg, be sure to invoke setpointers()
	1
Reading synapse information
Inserting 10 synapses
Unnamed: 0      0.000000
Dendrite       14.000000
Location        0.139538
Distance      116.315870
Delay          10.249518
Name: 0, dtype: float64
Unnamed: 0      1.000000
Dendrite        5.000000
Location        0.590493
Distance      184.839315
Delay           3.178268
Name: 1, dtype: float64
Unnamed: 0      2.000000
Dendrite        5.000000
Location        0.218638
Distance      125.874136
Delay          50.535529
Name: 2, dtype: float64
Unnamed: 0      3.000000
Dendrite       28.000000
Location        0.589266
Distance      287.073876
Delay          80.943046
Name: 3, dtype: float64
Unnamed: 0      4.000000
Dendrite       21.000000
Location        0.277871
Distance      179.285582
Delay          21.531376
Name: 4, dtype: float64
Unnamed: 0      5.000000
Dendrite        5.000000
Location        0.379927
Distance      149.460208
Delay          35.897938
Name: 5, dtype: float64
Unnamed: 0      6.000000
Dendrite       22.000000
Location        0.603726
Distance      160.043804
Delay          80.712827
Name: 6, dtype: float64
Unnamed: 0      7.000000
Dendrite        7.000000
Location        0.973116
Distance      210.756824
Delay          37.853438
Name: 7, dtype: float64
Unnamed: 0      8.000000
Dendrite       23.000000
Location        0.577352
Distance      255.118383
Delay          70.457184
Name: 8, dtype: float64
Unnamed: 0      9.000000
Dendrite        2.000000
Location        0.661263
Distance      184.257752
Delay          77.306834
Name: 9, dtype: float64

In [7]:
neuron.synapse_info

   Unnamed: 0  Dendrite  Location    Distance      Delay
0           0        14  0.139538  116.315870  10.249518
1           1         5  0.590493  184.839315   3.178268
2           2         5  0.218638  125.874136  50.535529
3           3        28  0.589266  287.073876  80.943046
4           4        21  0.277871  179.285582  21.531376
5           5         5  0.379927  149.460208  35.897938
6           6        22  0.603726  160.043804  80.712827
7           7         7  0.973116  210.756824  37.853438
8           8        23  0.577352  255.118383  70.457184
9           9         2  0.661263  184.257752  77.306834